version: "3.3"
services:
    moosh:
        image: ulysseus/moosh:0.1
        restart: unless-stopped
        volumes:
            - ${MOODLE_RUNTIME_DIR}:/var/www/html/${URL_DIRECTORY_ON_WEB_SERVER}
            - ${CONFIG_PHP_FILE}:/var/www/html/${URL_DIRECTORY_ON_WEB_SERVER}/config.php
            - ${MYSQL_PASSWORD_FILE}:/run/secrets/moodle-db.pass
            - ${MOODLE_DATA_DIR}:/var/www/moodledata
            - ./data:/var/www/mooshdata
